on: 
    push:
      branches:
        - main
    workflow_dispatch:     
name: Deploy website on push
  
jobs:
    run_pull:
      name: Deploy
      runs-on: ubuntu-latest

      steps:
        - name: executing remote ssh commands using ssh keys
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
                export NVM_DIR=~/.nvm 
                source ~/.nvm/nvm.sh
                cd ${{ secrets.WORK_DIR }}
                git fetch
                git checkout ${{ secrets.MAIN_BRANCH }}
                git pull
                npm install
                npm run build
                
              
